name: Build and push container images for testing

on:
  push:
    branches:
    - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        image-name:
        - k8s-hub
        - sssd

    steps:

    - name: Get Git repository
      uses: actions/checkout@v3

    - name: Set build tag
      id: build-tag
      run: echo "::set-output name=tag::build-$(date +%Y%m%d-%H%M)"

    - name: Set version tag
      id: version-tag
      run: echo "::set-output name=tag::latest"

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log into OSG Hub
      uses: docker/login-action@v1
      with:
        registry: hub.opensciencegrid.org
        username: ${{ secrets.HUB_USERNAME }}
        password: ${{ secrets.HUB_TOKEN }}

    - name: Build and push image
      uses: docker/build-push-action@v2
      with:
        context: docker/${{ matrix.image-name }}
        push: true
        tags: |
          hub.opensciencegrid.org/osg-jupyter/${{ matrix.image-name }}:sha-${{ github.sha }}
          hub.opensciencegrid.org/osg-jupyter/${{ matrix.image-name }}:${{ steps.build-tag.outputs.tag }}
          hub.opensciencegrid.org/osg-jupyter/${{ matrix.image-name }}:${{ steps.version-tag.outputs.tag }}
